### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [Achamoth/CITS3002_Networks-Project#32]
Hey Achamoth!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by assignguard-support** [comment]
:wave: gentle reminder!

**Comment by Achamoth** [comment]
Hi,

Could you please specify what part of this repo has been flagged as breaching anyone’s copyright?

All of the work in the repo was produced by and belongs to myself and the group members I worked with.

**Comment by sK0pe** [comment]
> Hey Achamoth!
> 
> This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.
> 

Which entity has flagged this code as being an infringement of "academic copyright" or an "institution's academic integrity policy".  This seems to be a broad and unfounded statement.  In reading the above comment it appears the author is unsure of what or if anything at all is being infringed.

> At your earliest convenience, please do one of the following:
> 
> * disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
> * remove any content could be in violation of copyright law
> * remove any content could be in violation of an institution's academic integrity policy
> 
> Please feel free to continue any discussion here. Thanks!

Since all of this code was coded originally by myself or @Achamoth, I see no need to comply.

If you object please notify us by end of business day Western Australian time (UTC +8) the 4th of November.
If no further discussion is received we will close this issue.

**Comment by yiweizhang526** [comment]
> > Hey Achamoth!
> > This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.
> 
> Which entity has flagged this code as being an infringement of "academic copyright" or an "institution's academic integrity policy". This seems to be a broad and unfounded statement. In reading the above comment it appears the author is unsure of what or if anything at all is being infringed.
> 
> > At your earliest convenience, please do one of the following:
> > 
> > * disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
> > * remove any content could be in violation of copyright law
> > * remove any content could be in violation of an institution's academic integrity policy
> > 
> > Please feel free to continue any discussion here. Thanks!
> 
> Since all of this code was coded originally by myself or @Achamoth, I see no need to comply.
> 
> If you object please notify us by end of business day Western Australian time (UTC +8) the 4th of November 2022. If no further discussion is received we will close this issue.

HI! what happened after your response 21 days ago?
